services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    image: git.pku.edu.cn/uaaa/server:${TAG:-latest}

  ui:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    image: git.pku.edu.cn/uaaa/ui:${TAG:-latest}
