version: '3.8'

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - '4180:4180'
    environment:
      OAUTH2_PROXY_PROVIDER: 'oidc'
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: 'UAAA'
      OAUTH2_PROXY_CLIENT_ID: 'org.fedstack.test'
      OAUTH2_PROXY_CLIENT_SECRET:
      OAUTH2_PROXY_REDIRECT_URL: 'http://localhost:4180/oauth2/callback'
      OAUTH2_PROXY_OIDC_ISSUER_URL: 'http://localhost:3000'
      OAUTH2_PROXY_UPSTREAMS: 'http://nginx:80'
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_INSECURE_OIDC_SKIP_NONCE: 'false'
      # OAUTH2_PROXY_CODE_CHALLENGE_METHOD: 'S256'
    network_mode: host

  nginx:
    image: nginx:latest
